openapi: 3.0.0
info:
  title: Financial Advisor Opportunity Backend API
  description: Backend service for the financial advisor frontend.
  version: "1.0"
servers:
  - url: http://localhost:8081
    description: Development server
paths:
  /activity/fetch-activity:
    get:
      summary: Fetch Activity
      description: Retrieves activity data for a specific lead.
      operationId: fetchActivity
      parameters:
        - name: idlead
          in: query
          required: true
          description: The ID of the lead for which activities are to be fetched.
          schema:
            type: string
            example: "c9357f00e6524ef7ba0b045dbfcfeba5"
        - name: authorization
          in: header
          required: true
          description: Bearer token for authorization.
          schema:
            type: string
            example: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIs..."
      responses:
        '200':
          description: Activity data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: HTTP status code
                    example: 200
                  message:
                    type: string
                    description: Status message
                    example: "Activity data retrieved successfully"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        idactivity:
                          type: string
                          description: Unique identifier for the activity
                          example: "ee527d7e2533f6dcb0587f58cdc3a684"
                        idlead:
                          type: string
                          description: ID of the lead associated with the activity
                          example: "c9357f00e6524ef7ba0b045dbfcfeba5"
                        idmeta_activity:
                          type: string
                          description: Metadata ID for the activity
                          example: "d10476cbca944b4984cf2f3237a6afd4"
                        firstname:
                          type: string
                          description: First name of the user associated with the activity
                          example: "Abhishek"
                        middlename:
                          type: string
                          nullable: true
                          description: Middle name of the user associated with the activity
                          example: null
                        lastname:
                          type: string
                          description: Last name of the user associated with the activity
                          example: "M"
                        fullname:
                          type: string
                          description: Full name of the user associated with the activity
                          example: "Abhishek M"
                        identity:
                          type: string
                          description: Unique identity reference
                          example: "5dceb723474645b1b5958eda0d97f6c2"
                        meta_data_name:
                          type: string
                          description: Name of the metadata associated with the activity
                          example: "Set Reminder"
        '401':
          description: Unauthorized - Invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized - Invalid token."
        '400':
          description: Bad Request - Missing parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ID lead is required."
                    
  /activity/create-activity:
    post:
      summary: Create Activity
      description: Inserts a new activity for a specific lead.
      operationId: createActivity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idLead:
                  type: string
                  description: The ID of the lead for which the activity is created.
                  example: "c9357f00e6524ef7ba0b045dbfcfeba5"
                idmetaActivity:
                  type: string
                  description: Metadata ID for the activity.
                  example: "d10476cbca944b4984cf2f3237a6afd4"
                idmetaTitleActivity:
                  type: string
                  description: Metadata ID for the activity title.
                  example: "64d1ff54973d4c19a79d09e7a7a74a8a"
                activeFlag:
                  type: integer
                  description: Flag indicating if the activity is active (1 for active, 0 for inactive).
                  example: 1
      parameters:
        - name: authorization
          in: header
          required: true
          description: Bearer token for authorization.
          schema:
            type: string
            example: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIs..."
      responses:
        '200':
          description: Activity inserted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: HTTP status code
                    example: 200
                  message:
                    type: string
                    description: Status message
                    example: "Activity inserted successfully"
                  data:
                    type: object
                    nullable: true
        '401':
          description: Unauthorized - Invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized - Invalid token."
        '400':
          description: Bad Request - Missing or invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input data."
